name: MobAnnihilation
version: '${version}'
main: ru.peef.mobannihilation.MobAnnihilation
authors: [HimBanny, owoPeef]
depend: [PlaceholderAPI, WorldEdit]
commands:
  menu:
    description: Menu commands
  game:
    description: Команда для взаимодействия с игрой
  spectate:
    description: Команда для наблюдения
    permission: "game.moderation.spectate"
    aliases: [s, spec]
  npc:
    description: Команда для управления NPC
    permission: "game.admin.npc"
  world:
    description: Work with worlds
    permission: "game.admin.world"
permissions:
  game.admin.npc:
    default: op
  game.admin.world:
    default: op
  game.admin.add_level:
      default: op
  game.admin.add_progress:
      default: op
  game.admin.set_level:
      default: op
  game.admin.set_progress:
      default: op
  game.moderation.spectate:
    default: op