name: MobAnnihilation
version: '${version}'
main: ru.peef.mobannihilation.MobAnnihilation
authors: [HimBanny, owoPeef]
depend: [PlaceholderAPI, WorldEdit]
commands:
  npc:
    description: Команда для управления NPC
    permission: "game.npc"
  game:
    description: Команда для взаимодействия с игрой
  world:
    description: Select world
    permission: "world"
permissions:
  game.add:
    default: op
  game.stats.other:
    default: op