name: MobAnnihilation
version: '${version}'
main: ru.peef.mobannihilation.MobAnnihilation
authors: [HimBanny, owoPeef]
depend: [PlaceholderAPI, WorldEdit]
commands:
  npc:
    description: Команда для управления NPC
    permission: "game.npc"
  menu:
    description: Menu commands
    permission: "game.menu"
  game:
    description: Команда для взаимодействия с игрой
  world:
    description: World interaction
    permission: "game.world"
permissions:
  game.add:
    default: op
  game.stats.other:
    default: op